services:
  postgres:
    build: ./services/postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_admin_pass
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD_FILE: /run/secrets/db_user_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_admin_pass
      - db_user_pass
    networks:
      - sbjobs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_ADMIN} -d ${DB_NAME}"]
      interval: 30s
      retries: 20
  backend:
    build:
      context: ./services/backend
      target: production
    container_name: backend
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_PORT: 5432
      BACKEND_PORT: ${BACKEND_PORT}
      DB_PASSWORD_FILE: /run/secrets/db_user_pass
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      N8N_API_KEY_FILE: /run/secrets/n8n_api_key
      RUN_DB_MIGRATIONS: "true"
      SECURE_COOKIE: ${SECURE_COOKIE}
      HTTP_ONLY_COOKIE: ${HTTP_ONLY_COOKIE}
    secrets:
      - db_user_pass
      - jwt_secret
      - n8n_api_key
    networks:
      - sbjobs_network
    depends_on:
      postgres:
        condition: service_healthy

  userui:
    build:
      context: ./services/ui
      target: production
    container_name: userui
    restart: unless-stopped
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-4000}
    ports:
      - "8080:80"
    networks:
      - sbjobs_network
    depends_on:
      - backend

  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION:-stable}
    container_name: n8n
    restart: unless-stopped
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: ${DB_NAME}
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: ${DB_USER}
      DB_POSTGRESDB_PASSWORD_FILE: /run/secrets/db_user_pass
      N8N_ENCRYPTION_KEY_FILE: /run/secrets/n8n_encryption_key
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      NODE_ENV: production
      N8N_PORT: ${N8N_PORT:-5678}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-UTC}
      TZ: ${GENERIC_TIMEZONE:-UTC}
    volumes:
      - n8n_data:/home/node/.n8n
    secrets:
      - db_user_pass
      - n8n_encryption_key
    networks:
      - sbjobs_network
    depends_on:
      postgres:
        condition: service_healthy
networks:
  sbjobs_network:
    driver: bridge
    name: sbjobs_network

secrets:
  db_admin_pass:
    file: ./secrets/postgres_admin_pass.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  db_user_pass:
    file: ./secrets/postgres_user_pass.txt
  n8n_encryption_key:
    file: ./secrets/n8n_encryption_key.txt
  n8n_api_key:
    file: ./secrets/n8n_api_key.txt

volumes:
  db_data:
  n8n_data:
