services:
  postgres:
    ports:
      - "${POSTGRES_PORT}:5432"

  migrator:
    environment:
      AUTO_REBUILD_ON_CHANGE: true

  backend:
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules