export const resourceDefinitions = {
  users: {
    path: 'users',
    table: 'users',
    idColumn: 'id',
    ownership: { type: 'selfUser' },
    allowCreate: false,
    fields: {
      email: { type: 'string' },
      first_name: { type: 'string' },
      last_name: { type: 'string' },
      phone: { type: 'string' },
      avatar: { type: 'string' },
    },
    createRequired: ['email'],
    hasUpdatedAt: true,
  },
  user_profiles: {
    path: 'user-profiles',
    table: 'user_profiles',
    idColumn: 'user_id',
    ownership: { type: 'userColumn', userColumn: 'user_id' },
    allowCreate: true,
    fields: {
      country: { type: 'string' },
      city: { type: 'string' },
      linkedin_url: { type: 'string' },
      github_url: { type: 'string' },
      portfolio_url: { type: 'string' },
      years_experience: { type: 'integer' },
      desired_salary_min: { type: 'number' },
      desired_salary_max: { type: 'number' },
      availability: { type: 'string' },
    },
    createRequired: [],
    hasUpdatedAt: true,
  },
  user_cv_templates: {
    path: 'user-cv-templates',
    table: 'user_cv_templates',
    idColumn: 'id',
    ownership: { type: 'userColumn', userColumn: 'user_id' },
    allowCreate: true,
    fields: {
      title: { type: 'string' },
      summary: { type: 'string' },
      is_default: { type: 'boolean' },
    },
    createRequired: ['title'],
    hasUpdatedAt: true,
  },
  user_cv_sections: {
    path: 'user-cv-sections',
    table: 'user_cv_sections',
    idColumn: 'id',
    ownership: {
      type: 'existsJoin',
      predicate:
        'EXISTS (SELECT 1 FROM user_cv_templates uct WHERE uct.id = t.cv_template_id AND uct.user_id = $%USER_PARAM%)',
    },
    createGuard: {
      sql: 'SELECT EXISTS (SELECT 1 FROM user_cv_templates WHERE id = $1 AND user_id = $2) AS allowed',
      sourceField: 'cv_template_id',
    },
    allowCreate: true,
    fields: {
      cv_template_id: { type: 'integer' },
      section_type: {
        type: 'string',
        enum: ['experience', 'education', 'skills', 'languages', 'projects', 'certifications', 'custom'],
      },
      position: { type: 'integer' },
      content_json: { type: 'object' },
    },
    createRequired: ['cv_template_id', 'section_type', 'position'],
    hasUpdatedAt: true,
  },
  companies: {
    path: 'companies',
    table: 'companies',
    idColumn: 'id',
    ownership: { type: 'none' },
    fields: {
      name: { type: 'string' },
      website: { type: 'string' },
      industry: { type: 'string' },
      size_range: { type: 'string' },
      country: { type: 'string' },
      city: { type: 'string' },
    },
    createRequired: ['name'],
    hasUpdatedAt: true,
  },
  company_contacts: {
    path: 'company-contacts',
    table: 'company_contacts',
    idColumn: 'id',
    ownership: { type: 'none' },
    fields: {
      company_id: { type: 'integer' },
      full_name: { type: 'string' },
      role: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string' },
      is_primary: { type: 'boolean' },
    },
    createRequired: ['company_id'],
    hasUpdatedAt: true,
  },
  job_offers: {
    path: 'job-offers',
    table: 'job_offers',
    idColumn: 'id',
    ownership: { type: 'none' },
    fields: {
      company_id: { type: 'integer' },
      title: { type: 'string' },
      description: { type: 'string' },
      requirements: { type: 'string' },
      employment_type: { type: 'string' },
      modality: { type: 'string' },
      location_text: { type: 'string' },
      salary_min: { type: 'number' },
      salary_max: { type: 'number' },
      currency: { type: 'string' },
      source_url: { type: 'string' },
      external_ref: { type: 'string' },
      status: { type: 'string', enum: ['open', 'closed', 'paused'] },
      published_at: { type: 'string', format: 'date-time' },
    },
    createRequired: ['company_id', 'title'],
    hasUpdatedAt: true,
  },
  job_offer_contacts: {
    path: 'job-offer-contacts',
    table: 'job_offer_contacts',
    idColumn: 'id',
    ownership: { type: 'none' },
    fields: {
      job_offer_id: { type: 'integer' },
      company_contact_id: { type: 'integer' },
      email_override: { type: 'string' },
      notes: { type: 'string' },
    },
    createRequired: ['job_offer_id'],
    hasUpdatedAt: false,
  },
  applications: {
    path: 'applications',
    table: 'applications',
    idColumn: 'id',
    ownership: { type: 'userColumn', userColumn: 'user_id' },
    allowCreate: true,
    fields: {
      job_offer_id: { type: 'integer' },
      status: {
        type: 'string',
        enum: [
          'draft',
          'cv_generated',
          'approved_by_user',
          'submitted',
          'in_review',
          'interview',
          'offer',
          'accepted',
          'rejected',
          'withdrawn',
        ],
      },
      applied_at: { type: 'string', format: 'date-time' },
      submitted_at: { type: 'string', format: 'date-time' },
      source_channel: { type: 'string' },
      external_application_id: { type: 'string' },
      notes: { type: 'string' },
    },
    createRequired: ['job_offer_id'],
    hasUpdatedAt: true,
  },
  application_cv_versions: {
    path: 'application-cv-versions',
    table: 'application_cv_versions',
    idColumn: 'id',
    ownership: {
      type: 'existsJoin',
      predicate:
        'EXISTS (SELECT 1 FROM applications a WHERE a.id = t.application_id AND a.user_id = $%USER_PARAM%)',
    },
    createGuard: {
      sql: 'SELECT EXISTS (SELECT 1 FROM applications WHERE id = $1 AND user_id = $2) AS allowed',
      sourceField: 'application_id',
    },
    allowCreate: true,
    fields: {
      application_id: { type: 'integer' },
      base_cv_template_id: { type: 'integer' },
      version_number: { type: 'integer' },
      summary_customized: { type: 'string' },
      content_json: { type: 'object' },
      generated_by: { type: 'string', enum: ['n8n', 'manual'] },
    },
    createRequired: ['application_id', 'version_number'],
    hasUpdatedAt: false,
  },
  application_events: {
    path: 'application-events',
    table: 'application_events',
    idColumn: 'id',
    ownership: {
      type: 'existsJoin',
      predicate:
        'EXISTS (SELECT 1 FROM applications a WHERE a.id = t.application_id AND a.user_id = $%USER_PARAM%)',
    },
    createGuard: {
      sql: 'SELECT EXISTS (SELECT 1 FROM applications WHERE id = $1 AND user_id = $2) AS allowed',
      sourceField: 'application_id',
    },
    allowCreate: true,
    fields: {
      application_id: { type: 'integer' },
      event_type: { type: 'string' },
      event_at: { type: 'string', format: 'date-time' },
      actor: { type: 'string', enum: ['system', 'user'] },
      payload_json: { type: 'object' },
    },
    createRequired: ['application_id', 'event_type', 'actor'],
    hasUpdatedAt: false,
  },
  application_attachments: {
    path: 'application-attachments',
    table: 'application_attachments',
    idColumn: 'id',
    ownership: {
      type: 'existsJoin',
      predicate:
        'EXISTS (SELECT 1 FROM applications a WHERE a.id = t.application_id AND a.user_id = $%USER_PARAM%)',
    },
    createGuard: {
      sql: 'SELECT EXISTS (SELECT 1 FROM applications WHERE id = $1 AND user_id = $2) AS allowed',
      sourceField: 'application_id',
    },
    allowCreate: true,
    fields: {
      application_id: { type: 'integer' },
      attachment_type: { type: 'string' },
      file_name: { type: 'string' },
      storage_url: { type: 'string' },
      mime_type: { type: 'string' },
    },
    createRequired: ['application_id', 'attachment_type', 'storage_url'],
    hasUpdatedAt: false,
  },
};

export const resourceList = Object.values(resourceDefinitions);
