# ==============================================
# CONFIGURACIÓN DE POSTGRESQL (PARA VPS 4GB RAM)
# ==============================================

# -----------------------------
# 1. Conexiones
# -----------------------------
listen_addresses = '*'
max_connections = 100

# -----------------------------
# 2. Memoria y Rendimiento
# -----------------------------
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
work_mem = 16MB

# -----------------------------
# 3. Escritura y Seguridad de Datos (WAL)
# -----------------------------
wal_level = replica
checkpoint_completion_target = 0.9
max_wal_size = 2GB
min_wal_size = 80MB

# -----------------------------
# 4. Idioma y Formato
# -----------------------------
datestyle = 'iso, mdy'
timezone = 'UTC'

# -----------------------------
# 5. Logs (Básico)
# -----------------------------
log_timezone = 'UTC'
log_min_duration_statement = 1000 # Loguea consultas que tarden más de 1 segundo